config/routes.rb
Rails.application.routes.draw do
	get 'jobs/jobs_results'
	root to: 'jobs#jobs_results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

def jobs_results
    technology = params[:technology]
    location = params[:location]
    country = params[:country]
    start = params[:start]
    response = HTTParty.get("http://api.indeed.com/ads/apisearch?publisher=7277146494571922&q=#{technology}&co=#{country}&l=#{location}&start=#{start.to_i*10}&format=json&v=2")
    @job_results = response.parsed_response
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/jobs_results.html.erb
<div class="row">
<div class="col-md-8">


<div class= "page-header">
 <h2>Total <%= @job_results["query"] %> jobs<small> in <%= @job_results["location"] %> is <%= @job_results["totalResults"] %> </small></h2>
 </div>
 <table class= "table table-striped" id="myTable">
 	<thead>
 		<tr>
 			<th>Title</th>
 			<th>Company</th>
 			<th>City</th>
 			<th>Source</th>
 			<th>Snippet</th>
 		</tr>
 	</thead>
 	<tbody>
 	<% @job_results["results"].each do |result| %>
 	<tr>
 		<td><%= result["jobtitle"] %></td>
 		<td><%= result["company"] %></td>
 		<td><%= result["city"] %></td>
 		<td><%= result["source"] %></td>
 		<td><%= raw(result["snippet"]) %></td>
 	</tr>
 	<% end %>
 	</tbody>
 </table>
 </div>

 <div class="col-md-4">     <div class="page-header">     <h3>Search</h3>
</div>     <%= form_tag(jobs_jobs_results_path, method: :get) do %>     <div
class= "form-group">         <label>Technology: </label><br/>         <%=
text_field_tag :technology %>     </div>

 	<div class= "form-group">
 		<label>Location: </label><br/>
 		<%= text_field_tag :location %>
 	</div>
 	<div class= "form-group">
 		<label>Country: </label><br/>
 		<%= text_field_tag :country %>
 	</div>
 	<div class= "form-group">
 		<label>Page: </label><br/>
 		<%= text_field_tag :start %>
 	</div>
 	<%= submit_tag "Search", class:"btn btn-primary" %>

 	<% end %>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aeroleads</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>